feat: add root user support
SeisoLLC/easy_infra pull request #251
Opened 2023-05-08 18:00 UTC by JonZeolla

# Contributor Comments

This adds support for the `root` user at runtime, in parallel to `easy_infra`.  Below are the tests that I updated/considered:

Everyting run_tests calls needs user except container-global
- run_path_check - DONE
  - check_paths - DONE
- run_env - DONE
  - run_aws - DONE
  - run_azure - DONE
- run_tool - DONE
  - run_cloudformation - DONE
  - run_ansible - DONE
  - run_terraform - DONE
- global_tests - DONE
  - test_version_arguments - DONE
  - test_sh - DONE
- run_security - NOT NEEDED
- All of the exec_tests need to be passed a user - DONE
  - Set it to fail closed if this is forgotten.
- Fix the input of test to specify a user and not "all" - DONE

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [X] Rebase your branch against the latest commit of the target branch
- [X] If you are adding a dependency, please explain how it was chosen
- [X] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
- [X] If there is an issue associated with your Pull Request, link the issue to the PR.

2023-05-09 10:47 UTC, JonZeolla commented on build/Dockerfile.base
> + && apt-get remove -y ssh \
This file has the only meaningful changes everything else is testing related.

2023-05-09 18:55 UTC, JonZeolla commented on build/Dockerfile.base
> - && echo "export PATH=/home/easy_infra/.local/bin:${PATH}" >> /home/easy_infra/.bashrc \
We are now using a venv instead of `--user` pip installs

2023-05-10 10:50 UTC, digeseiso commented
> # Contributor Comments
> This adds support for the `root` user at runtime, in parallel to `easy_infra`. Below are the tests that I updated/considered:
> 
> Everyting run_tests calls needs user except container-global
> 
> * run_path_check - DONE
>   
>   * check_paths - DONE
> * run_env - DONE
>   
>   * run_aws - DONE
>   * run_azure - DONE
> * run_tool - DONE
>   
>   * run_cloudformation - DONE
>   * run_ansible - DONE
>   * run_terraform - DONE
> * global_tests - DONE
>   
>   * test_version_arguments - DONE
>   * test_sh - DONE
> * run_security - NOT NEEDED
> * All of the exec_tests need to be passed a user - DONE
>   
>   * Set it to fail closed if this is forgotten.
> * Fix the input of test to specify a user and not "all" - DONE
> 
> ## Pull Request Checklist
> Thank you for submitting a contribution to `easy_infra`!
> 
> In order to streamline the review of your contribution we ask that you review and comply with the below requirements:
> 
> * [x]  Rebase your branch against the latest commit of the target branch
> * [x]  If you are adding a dependency, please explain how it was chosen
> * [x]  If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
> * [x]  If there is an issue associated with your Pull Request, link the issue to the PR.

@JonZeolla i think we should add some comments on why we decided to add support. Also i think we should update the docs to advise the user to run as root if they need to use easy_infra in github actions

2023-05-10 11:12 UTC, digeseiso commented on easy_infra/utils.py
> +    return users
Wouldnt it be better to fail immediately if the provided user does not exist?
```suggestion
def gather_users(*, user: str) -> list[str]:
    """Return a list of users, based on the simplified provided user"""
    if user not in constants.USERS:
         LOG.error(f"{user} is not a supported user, exiting...")
         sys.exit(1)
     elif user == "all":
           users: list[str] = constants.USERS
      else:
            users: list[str] = [user]
```

2023-05-10 11:49 UTC, digeseiso requested changes
@JonZeolla i think we should add some comments on why we decided to add support for the root user. Also i think we should update the docs to advise users to run as root if they need to use easy_infra in github actions and perhaps link the documents show that running as a non-root user is not supported? or maybe simply mentioning it is enough?.

The [contributing.md](https://github.com/SeisoLLC/easy_infra/blob/80c6e31a8015d50b6a5812a5d8cc6dc1de018ee2/CONTRIBUTING.md?plain=1#L70) talks about ensuring that the user from inside the container can write to the host, i think we could also update that to somewhat reflect that a new root user is available and maybe mention github actions there? You decide

Even though it appears that containers run by default as the easy_infra user, do we also want to add a security disclaimer about running the container as root or just expect that the users will know?

2023-05-10 13:17 UTC, JonZeolla commented
@digeseiso I only updated the tech details because while it works I don’t want people to potentially use it and make an insecure environment. Instead I plan to point people to our GitHub action, etc for those use cases.

2023-05-10 13:39 UTC, JonZeolla commented
@digeseiso added a mention in the tech docs on why we added the root user support, but that you should prefer the default still

2023-05-10 16:30 UTC, merged