Add tests
SeisoLLC/easy_infra pull request #61
Opened 2021-01-26 00:48 UTC by JonZeolla

# Contributor Comments
This is adds tests to `easy_infra`.

## Pull Request Checklist
Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:
 - [X] Rebase your branch against the latest commit of the target branch, which likely should be `main`
 - [X] If there is an issue associated with your Pull Request, align your PR title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

2021-01-26 10:43 UTC, JonZeolla commented on tasks.py
> +        + str(CI_DEPENDENCIES["not pinned"])
No longer need str()

2021-01-26 11:08 UTC, JonZeolla commented on tasks.py
> +        if target == "minimal":
Add security scanning to each stage

2021-01-26 14:27 UTC, JonZeolla commented on tasks.py
> +def run_security_tests(*, image: str):
This needs to be updated to run off of the recently built images.  Right now it pulls from docker hub, which is not accurate as of this PR.

2021-01-29 21:08 UTC, pb-seiso requested changes
Looks pretty good, mostly just noted some ideas on how to refactor & clean up a bit.

2021-01-29 21:08 UTC, pb-seiso commented on tasks.py
> +        if target == "minimal":
Nit: recommend using constants for each `target` in this statement.

2021-01-29 21:12 UTC, JonZeolla commented on tasks.py
> +    return response
It's returning a dictionary which is what `containers.run` returns with an added key of `logs` with a value of the logs formatted as a singer line.

2021-01-29 21:14 UTC, JonZeolla commented on tasks.py
> +def expected_status_code(*, expected: int, response: dict) -> bool:
Changed to `is_status_expected()`

2021-01-29 21:16 UTC, JonZeolla commented on tasks.py
> +TESTS_PATH = CWD.joinpath("tests")
I am trying to keep the config file focused on defining the desired runtime config

2021-01-29 21:17 UTC, pb-seiso commented on tasks.py
> +    return response
Thanks, I meant `dict`. It looks like you're only parsing out the status code and the logs so it feels like the latter could get appended separately. I've never been a fan of complex return values - your call though.

2021-01-29 21:22 UTC, JonZeolla commented on tasks.py
> +    if os.environ.get("GITHUB_ACTIONS") == "true":
I'm pretty sure there's no such thing in `python3` 🤔

2021-01-29 21:24 UTC, JonZeolla commented on tasks.py
> +    )
Nothing in the function precludes it from being moved to another project; are you saying we need a more detailed task than `test` like `security_test`?  I don't understand why you would want that

2021-01-29 21:24 UTC, JonZeolla commented on tasks.py
> +    command = (
I moved them to vars

2021-01-29 21:26 UTC, JonZeolla commented on tasks.py
> +def run_terraform_tests(*, image: str):
Yeah I agree but because of the global variables that's a refactoring effort I would prefer to separate from this PR.

2021-01-29 21:29 UTC, pb-seiso commented on tasks.py
> +    if os.environ.get("GITHUB_ACTIONS") == "true":
Right, I mean defining it as a variable the same way you have `CONFIG_FILE` etc:

`ENV_GITHUB_ACTIONS="GITHUB_ACTIONS"`

2021-01-29 22:03 UTC, tp-seiso commented on tests/terraform/invalid/invalid.tf
> +    port     = "65535"
```suggestion
    #invalid due to missing required arguments
    port     = "65535"
```

2021-01-29 22:10 UTC, tp-seiso commented on tests/terraform/insecure/insecure.tf
> +  ami           = data.aws_ami.ubuntu.id
```suggestion
  # fails checkov checks CKV_AWS_8 and CKV_AWS_79
  ami           = data.aws_ami.ubuntu.id
```

2021-01-29 22:28 UTC, JonZeolla commented on tasks.py
> +    """Check to see if the status code was expected"""
I dig it; done.

2021-02-01 04:38 UTC, tp-seiso approved these changes
built and tested locally without issues, all pass. Framework looks good and extensible to expand testing

2021-02-01 14:11 UTC, pb-seiso approved these changes
Really like the switch to Invoke and the new testing approach. Looks great.

2021-02-01 14:11 UTC, merged