Document a use case for Terraform
SeisoLLC/easy_infra pull request #77
Opened 2021-03-29 19:32 UTC by tpears

# Contributor Comments

This branch introduces M2R2 and Sphinx which allow for the existing README to be ported to RST and for HTML to be auto-generated from the new RST documentation. The documentation site can be built locally after installing the updated pipenv dev packages by running the following command from the base directory:
`pipenv run sphinx-build -M html docs/ docs/_build`

You can then view the page by pointing a browser to your local file system. 

This branch was also built on readthedocs.io and can be viewed here: https://easy-infra.readthedocs.io/en/use-cases/

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [x] Rebase your branch against the latest commit of the target branch, which likely should be `main`
- [x] If there is an issue associated with your Pull Request, align your PR title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

2021-03-29 23:09 UTC, JonZeolla requested changes
Looking pretty good, just some tweaks

2021-03-29 23:09 UTC, JonZeolla commented on docs/Terraform/index.rst
> +to support its use in CI/CD pipelines. You can use easy_infra to execute Terraform commands on an up-to-date version
```suggestion
to support its use, both locally and in CI/CD pipelines. You can use easy_infra to execute Terraform commands, and
```

2021-03-29 23:09 UTC, JonZeolla commented on docs/Terraform/index.rst
> +of the program. As part of the terraform execution, security checks available from `Checkov <https://www.checkov.io/>`_, `tfsec <https://tfsec.dev/>`_, and `Terrascan <https://www.accurics.com/produc
```suggestion
as part of the execution, security checks available from `Checkov <https://www.checkov.io/>`_, `tfsec <https://tfsec.dev/>`_, and `Terrascan <https://www.accurics.com/products/terrascan/>`_ are transparently performed to assess your terraform code.
```

2021-03-29 23:09 UTC, JonZeolla commented on docs/Terraform/index.rst
> +    docker run -v $(pwd):/tf seiso/easy_infra:latest-minimal terraform validate
```suggestion
    docker run -v $(pwd):/iac seiso/easy_infra:latest-minimal terraform validate
```

2021-03-29 23:09 UTC, JonZeolla commented on docs/Terraform/index.rst
> +    docker run -v $(pwd):/tf seiso/easy_infra:latest-minimal /bin/bash -c "terraform plan && terraform apply -auto-approve"
```suggestion
    docker run -v $(pwd):/iac seiso/easy_infra:latest-minimal /bin/bash -c "terraform plan && terraform apply -auto-approve"
```

2021-03-29 23:09 UTC, JonZeolla commented on docs/Terraform/index.rst
> +    docker run -v $(pwd):/tf -v $(pwd)/plugin-cache:/root/.terraform.d/plugin-cache easy_infra:latest-minimal /bin/bash -c "terraform init; terraform version"
```suggestion
    docker run -v $(pwd):/iac -v $(pwd)/plugin-cache:/root/.terraform.d/plugin-cache easy_infra:latest-minimal /bin/bash -c "terraform init; terraform validate"
```

2021-03-29 23:09 UTC, JonZeolla commented on docs/Terraform/index.rst
> +Open Policy Agent (OPA) offers useful resources for cloud native infrastructure administrators.
```suggestion
Configuring custom checks can be done by leveraging the robust Rego language, maintained by the
Open Policy Agent (OPA) project, and used as a part of `terrascan` for managing cloud native infrastructure.
```

2021-03-29 23:09 UTC, JonZeolla commented on docs/index.rst
> +   AWS Cli <awscli/index>
```suggestion
   AWS CLI <awscli/index>
```

2021-03-29 23:09 UTC, JonZeolla commented on docs/index.rst
> +* :ref:`modindex`
Broken link?

2021-03-29 23:09 UTC, JonZeolla commented on docs/index.rst
> +* :ref:`genindex`
Empty page?

2021-03-29 23:09 UTC, JonZeolla commented on docs/Terraform/index.rst
> +If you use Software Version Control to manage your Terraform IaC, consider executing ``terraform validate`` with
```suggestion
If you use Software Version Control (such as `git`) to manage your Terraform IaC, consider executing ``terraform validate`` with 
```

2021-03-31 20:35 UTC, JonZeolla commented on docs/requirements.txt
> +m2r2==0.2.7
The way I've done this in the past is [this](https://github.com/SeisoLLC/easy_sast/blob/d99154ab42b91a8cdf22a2889913324ec007acc7/Makefile#L83).  I think we have some private projects too that do this via `tasks.py` already but I couldn't quickly find them

2021-04-14 13:26 UTC, tpears commented on docs/requirements.txt
> +m2r2==0.2.7
Tracking in https://github.com/SeisoLLC/easy_infra/issues/81

2021-04-26 12:58 UTC, tpears commented
Missed comments that were collapsed. Accepted all the remaining suggestions.

2021-04-27 17:54 UTC, JonZeolla requested changes
@tpears please address the one typo comment I left and ensure that the details to deploy to read the docs are at least documented (I couldn't find it) if not automated as a part of CI/CD.  If needed we can do the automation as a follow-on, but need to ensure the docs render and deploy process is documented.

There's also a merge conflict to be addressed

2021-04-27 17:54 UTC, JonZeolla commented on docs/index.rst
> +   AWS ClI <awscli/index>
```suggestion
   AWS CLI <awscli/index>
```

2021-04-28 13:29 UTC, tpears commented
Documentation for automation is in a follow task. Typo corrected and pipfile merged to rebuild pipfile.lock in preparation for merge.

2021-04-28 23:37 UTC, JonZeolla approved these changes
Looks great, nice work @tpears

2021-04-28 23:37 UTC, merged